### ISSUE TITLE
Cannot read property `time` of null

### ISSUE THREAD

**Issue by aaronbuchanan** [wildpixeldesign/react-timeframe#2]
This package looks perfect for what I need, but I hit issues trying to use the example w/ react-native.

My code looks like:
```js
<Timeframe
  endTime={"2017-08-22T12:00:00Z"}
  onRender={function() {
    return (
      <Text style={styles.header}>
      ${this.state.time.hours}:${this.state.time.minutes}:${this.state.time.seconds}
      </Text>
    );
  }}
  />
```

Using the debugger I can see that `this.state` is `null` on the first call, 
if I use `onUpdate` and call `setState` then subsequent `onRender` calls can access `this.state.time`, but it doesn't actually count down? Am I missing something?

Redbox:
![image](https://user-images.githubusercontent.com/972337/29331301-eacbfb8c-81c9-11e7-8bf4-e020aaf02f66.png)

relevant output from `npm ls`:
```sh
└─┬ react-timeframe@0.1.0
  ├── moment@2.18.1
  ├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6 deduped
  ├─┬ react-mixin@3.1.0
  │ ├── object-assign@4.1.1 deduped
  │ └── smart-mixin@2.0.0
  └── react-timer-mixin@0.13.3 deduped
```

**Comment by aaronbuchanan** [comment]
Also noticed the example code is missing a closing tick in the onRender method.

**Comment by danmoore83** [comment]
Hey mate, 
I don't think the problem is ReactNative (thats what i used this for too).
Had a quick look at the source, and the documentation could be wrong. 

Try changing the prop 'endTime' to 'endsAt'. 

lmk how you go.

**Comment by aaronbuchanan** [comment]
Thanks for the reply @wildpixeldesign! 

I updated to pass the `endsAt` prop instead of `endTime` and this works, but doing so conflicts with the [docs](https://github.com/wildpixeldesign/react-timeframe#basic-usage). 

Also, the docs show `this.state.completed` which isn't defined on `this.state`. Am I missing something here?

Maybe docs are just out of date or I'm just confused?

**Comment by danmoore83** [comment]
It appears I wrote the docs incorrectly. I have update it to reflect the endsAt value in the code.

this state.completed is set inside the tick function, when the timer runs out.

<img width="394" alt="screen shot 2017-08-23 at 8 51 48 am" src="https://user-images.githubusercontent.com/411325/29591400-b9dd0cb4-87e1-11e7-92ea-743bc9a904cd.png">
